import { Product } from '../model/product';

export const ProductsResponseMock: Product[] = [
  {
    _id: '12345601',
    nombre: 'producto1',
    caracteristica: 'producto perecible',
    fechaLanzamiento: new Date(2020, 2, 15).toISOString(),
    email: 'test@gmail.com',
    paisFabricacion: 'Colombia',
    precio: 10.5,
    unidadesVendidas: 1,
    unidadesDisponibles: 10,
    imagenURL: '',
  },
  {
    _id: '12345602',
    nombre: 'producto1',
    caracteristica: 'producto perecible',
    fechaLanzamiento: new Date(2020, 2, 15).toISOString(),
    email: 'test@gmail.com',
    paisFabricacion: 'Colombia',
    precio: 10.5,
    unidadesVendidas: 1,
    unidadesDisponibles: 10,
    imagenURL: '',
  },
  {
    _id: '12345603',
    nombre: 'producto1',
    caracteristica: 'producto perecible',
    fechaLanzamiento: new Date(2020, 2, 15).toISOString(),
    email: 'test@gmail.com',
    paisFabricacion: 'Colombia',
    precio: 10.5,
    unidadesVendidas: 1,
    unidadesDisponibles: 10,
    imagenURL: '',
  },
  {
    _id: '12345604',
    nombre: 'producto1',
    caracteristica: 'producto perecible',
    fechaLanzamiento: new Date(2020, 2, 15).toISOString(),
    email: 'test@gmail.com',
    paisFabricacion: 'Colombia',
    precio: 10.5,
    unidadesVendidas: 1,
    unidadesDisponibles: 10,
    imagenURL: '',
  },
  {
    _id: '12345605',
    nombre: 'producto1',
    caracteristica: 'producto perecible',
    fechaLanzamiento: new Date(2020, 2, 15).toISOString(),
    email: 'test@gmail.com',
    paisFabricacion: 'Colombia',
    precio: 10.5,
    unidadesVendidas: 1,
    unidadesDisponibles: 10,
    imagenURL: '',
  },
  {
    _id: '12345606',
    nombre: 'producto1',
    caracteristica: 'producto perecible',
    fechaLanzamiento: new Date(2020, 2, 15).toISOString(),
    email: 'test@gmail.com',
    paisFabricacion: 'Colombia',
    precio: 10.5,
    unidadesVendidas: 1,
    unidadesDisponibles: 10,
    imagenURL: '',
  },
];
